# Generated by Django 5.0.7 on 2025-12-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_wallet_amount_invested'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_level',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id', 'Identity Document'), ('financial', 'Financial Records'), ('loan', 'Loan Agreement'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='kyc/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
