# Generated by Django 5.0.7 on 2025-12-13 00:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_profile_verification_level_kycdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('starter', 'Starter - Beginner Investors'), ('couples', 'Couples - Joint Investment'), ('retirement', 'Retirement - Long-term Growth'), ('education', "Education Fund - Child's Future"), ('travel', 'Travel Fund - Adventure Fund'), ('emergency', 'Emergency Fund - Safety Net'), ('wealth', 'Wealth Building - Premium'), ('crypto', 'Crypto Growth - High Risk/Reward')], max_length=20)),
                ('description', models.TextField()),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk - Conservative'), ('moderate', 'Moderate Risk - Balanced'), ('high', 'High Risk - Aggressive Growth')], max_length=10)),
                ('minimum_investment', models.DecimalField(decimal_places=2, default=100, max_digits=15)),
                ('recommended_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('maximum_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('expected_annual_return', models.DecimalField(decimal_places=2, help_text='Expected annual return percentage (0-100%)', max_digits=5)),
                ('historical_performance', models.DecimalField(blank=True, decimal_places=2, help_text='Historical average annual return percentage', max_digits=5, null=True)),
                ('crypto_allocation', models.IntegerField(default=0, help_text='Percentage allocated to cryptocurrencies', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('real_estate_allocation', models.IntegerField(default=0, help_text='Percentage allocated to real estate/property', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stocks_allocation', models.IntegerField(default=0, help_text='Percentage allocated to stocks', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bonds_allocation', models.IntegerField(default=0, help_text='Percentage allocated to bonds', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cash_allocation', models.IntegerField(default=0, help_text='Percentage allocated to cash/stablecoins', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recommended_duration_months', models.IntegerField(help_text='Recommended investment period in months')),
                ('early_withdrawal_penalty', models.DecimalField(decimal_places=2, default=0, help_text='Penalty percentage for early withdrawal', max_digits=5)),
                ('is_automated_rebalancing', models.BooleanField(default=True)),
                ('is_tax_optimized', models.BooleanField(default=False)),
                ('allows_monthly_contribution', models.BooleanField(default=True)),
                ('allows_lump_sum', models.BooleanField(default=True)),
                ('management_fee', models.DecimalField(decimal_places=2, default=1.5, help_text='Annual management fee percentage', max_digits=5)),
                ('current_aum', models.DecimalField(decimal_places=2, default=0, help_text='Current assets under management', max_digits=15)),
                ('number_of_investors', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'minimum_investment'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='core_invest_categor_7e2ac6_idx'), models.Index(fields=['risk_level'], name='core_invest_risk_le_080176_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvestmentPlanPromotionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_type', models.CharField(choices=[('welcome_bonus', 'Welcome Bonus'), ('referral', 'Referral Bonus'), ('milestone', 'Milestone Reward'), ('seasonal', 'Seasonal Promotion'), ('loyalty', 'Loyalty Reward')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('grant_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed bonus amount in USD', max_digits=15, null=True)),
                ('grant_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage-based bonus (e.g., 5% of investment)', max_digits=5, null=True)),
                ('minimum_investment_required', models.DecimalField(decimal_places=2, max_digits=15)),
                ('maximum_grant_per_user', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='core.investmentplan')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='PlanPortfolioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('crypto', 'Cryptocurrency'), ('stock', 'Stock/ETF'), ('bond', 'Bond/Fixed Income'), ('real_estate', 'Real Estate/Property'), ('commodity', 'Commodity'), ('cash', 'Cash/Stablecoin')], max_length=20)),
                ('symbol', models.CharField(help_text='e.g., BTC, AAPL, SPY', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of plan allocated to this asset', max_digits=5)),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=15)),
                ('price_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_assets', to='core.investmentplan')),
            ],
            options={
                'ordering': ['plan', '-allocation_percentage'],
            },
        ),
        migrations.CreateModel(
            name='UserInvestmentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_contributed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_returns', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('subscription_start_date', models.DateTimeField(auto_now_add=True)),
                ('planned_end_date', models.DateTimeField()),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('monthly_contribution', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly recurring contribution amount', max_digits=15, null=True)),
                ('next_contribution_date', models.DateTimeField(blank=True, null=True)),
                ('roi_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_rebalance_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.investmentplan')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_subscriptions', to='users.profile')),
            ],
            options={
                'ordering': ['-subscription_start_date'],
                'unique_together': {('user_profile', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyCotributionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('scheduled_date', models.DateField()),
                ('actual_contribution_date', models.DateField(blank=True, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_schedules', to='core.userinvestmentsubscription')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
    ]
